import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import localFont from 'next/font/local'

const recursive = localFont({
  src: '../assets/fonts/Recursive_VF_1.085.woff2',
  display: 'swap',
  weight: '350 1000',
  style: 'oblique 0deg 14deg',
  variable: '--vf-recursive'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={recursive.variable}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
